---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "api-app.fullname" . }}
  labels:
    {{- include "api-app.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.envsecret }}
  {{ if typeIs "float64" $v }}{{ $k }}: {{ $v | int64 | toString | trimSuffix "\n" | b64enc }}
  {{- else if $v }}{{ $k }}: {{ $v | trimSuffix "\n" | b64enc }}
  {{- else }}{{ $k }}: ''{{ end }}
  {{- end }}

