{{- $fullName := include "producer-app.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "producer-app.fullname" . }}
  labels:
    {{- include "producer-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "producer-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "producer-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "producer-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.container.port }}
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /swagger/index.html
          #     port: http
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   failureThreshold: 4
          # livenessProbe:
          #   httpGet:
          #     path: /swagger/index.html
          #     port: http
          #   initialDelaySeconds: 35
          #   periodSeconds: 10
          #   failureThreshold: 6
          envFrom:
          - configMapRef:
              name: {{ include "producer-app.fullname" . }}
          - secretRef:
              name: {{ include "producer-app.fullname" . }}
          volumeMounts:
          - name: {{ include "producer-app.fullname" . }}-secret
            mountPath: "/secret"
            readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ include "producer-app.fullname" . }}-secret
        secret:
          secretName: {{ include "producer-app.fullname" . }}-mount
          optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

